### ISSUE TITLE
 java: incompatible types error on compiling helloworld  

### ISSUE THREAD

**Issue by smritimehra** [thinkerou/karate-grpc#6]
Hi @thinkerou 

I am getting the following error when I try to compile your basic Helloworld package
 
Error:(34, 67) java: incompatible types: java.util.List<gherkin.formatter.model.Feature> cannot be converted to java.util.List<com.github.thinkerou.demo.helloworld.Feature>
Error:(71, 39) java: incompatible types: java.util.List<com.github.thinkerou.demo.helloworld.Feature> cannot be converted to java.util.List<gherkin.formatter.model.Feature>

**Comment by thinkerou** [comment]
@smritimehra How you run it? please see https://github.com/thinkerou/karate-grpc/blob/master/.travis.yml thanks!
